### ISSUE TITLE
Docs: delete (for now)

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/mosaic-contracts#116]
Delete `/docs/json` and `/docs/md`. TBD how best to provide documentation of protocol functionality.

**Comment by schemar** [comment]
@jasonklein this is assigned to you. Are you still working on this?

**Comment by jasonklein** [comment]
No, but it wasn't so much a thing to work on as a thing to do. But then before figuring out what best to do, it started being used again in relation to documenting 0.9.3 (and 0.9.2, in relation to that effort). I recommend consulting with Ben to determine how to handle.
