### ISSUE TITLE
Use generic object name in OpenSTValue and OpenSTUtility protocol transfer functions

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/mosaic-contracts#210]
`OpenSTValue` and `OpenSTUtility` name the items to have their protocols transferred `_simpleStake` and `_token`, respectively.

As future versions of the protocol will mean there are other items that are protocol versioned, the variable names of the items in the `OpenSTValue` and `OpenSTUtility` calls should be more generic (i.e., `_protocolVersioned`).

Ref: MOSA-46

**Comment by schemar** [comment]
@deepesh-kn are you still working on this? I assume it was closed in #212.
