### ISSUE TITLE
Remove _rlpEncodedAccount variable from Core contract proveOpenST function

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#216]
**Current Method Signature**

function proveOpenST(uint256 _blockHeight,bytes _rlpEncodedAccount,bytes _rlpParentNodes)

**Expected Method Signature**

function proveOpenST(uint256 _blockHeight,bytes _rlpParentNodes)

**Problem**

proveOpenST function has parameter _rlpEncodedAccount which can be extracted from _rlpParentNodes. This will simplify proveOpenST function for the caller. Also it reduces duplication of method parameters.

**Solution**

_rlpEncodedAccount data can be extracted from _rlpParentNodes variable.It can take extra gas cost in extracting _rlpEncodedAccount from _rlpParentNodes.

**Comment by schemar** [comment]
Dropped.
