### ISSUE TITLE
Return extra value token (if BT is valuable) to the staker if can't be converted to BT.

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenSTFoundation/mosaic-contracts#219]
Context: when BT is more valuable economy than Value Token, It is possible that some part of staking amount can't be minted to BT.
For example:

5VT wei =1BT wei
If user or partner company stakes 9 VT wei then only one 1 BT wei can be minted. 4 VT wei will be remainder.

Problem: With the current implementation remaining 4 VT  in the above example will be locked into SimpleStake contract.

Solution: During the staking process, calculate how much VT can be staked and minted in BT. Surplus VT should not be transferred from users account to OpenST-Value

**Comment by schemar** [comment]
@sarvesh-ost what is the status of this ticket? Was it closed in #213?
