### ISSUE TITLE
Create unit tests for uncovered lines in Workers.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#227]
* `Workers.sol` has the following coverage report 
60% Statements 9/15 
37.5% Branches 3/8 
50% Functions 3/6 
56.25% Lines 9/16
* Uncovered functions 
removeWorker, remove, approve

**Comment by noslav** [comment]
New report post adding new test cases on Workers.sol -
100% Statements 15/15
50% Branches 4/8
100% Functions 6/6
100% Lines 16/16
All functions are now covered.

**Comment by schemar** [comment]
Dropped.
