### ISSUE TITLE
Create unit tests for uncovered lines in RLPencode.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#229]
* `RLPEncode.sol` has the following coverage report 
24.14% Statements 7/29 
25% Branches 2/8 
40% Functions 2/5 
24.24% Lines 8/33
* Uncovered functions 
encodeItem, encodeList, encodeListWithPasses, encodeLength, getLengthBytes

**Comment by schemar** [comment]
Dropped.
