### ISSUE TITLE
Create unit tests for uncovered lines in RLP.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#230]
* `RLP.sol` has the following coverage report 
62.93% Statements 73/116
45.95% Branches 34/74
61.54% Functions 16/26
61.15% Lines 96/157
* Uncovered functions 
next, toRLPItem, isNull, isList(117), isData(133), isEmpty, items(167), toAscii, toBool, toByte, toInt, toAddress, _payloadOffset(382, 389, 393), validate

**Comment by schemar** [comment]
Dropped.
