### ISSUE TITLE
Create unit tests for uncovered lines in BytesLib.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#231]
* `BytesLib.sol` has the following coverage report 
18.75% Statements 3/16 
0% Branches 0/6 
28.57% Functions 2/7 
20% Lines 5/25
* Functions remaining to be covered 
slice, toBytes32, fromBytes32, toUint, toAddress

**Comment by noslav** [comment]
* Removed 2 redundant fns and added 6 new test cases 
* Solcover report now stands at -
100% Statements 9/9
100% Branches 6/6
100% Functions 5/5
100% Lines 17/17

**Comment by schemar** [comment]
Dropped.
