### ISSUE TITLE
Update description of OpenSTValue.stake to reflect changes in 0.9.3

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/mosaic-contracts#233]
The `@dev` documentation comment for `OpenSTValue.stake` currently states: "In order to stake the tx.origin needs to set an allowance for the OpenSTValue contract to transfer to itself to hold during the staking process."

This is inaccurate as of `0.9.3` and should be updated to reflect that the utility token's staking account (the respective `Gateway`, in practice) is what is needs to set an allowance.

This is a hotfix that should be completed on the release branch.

**Comment by schemar** [comment]
@jasonklein what is the status of this? I assume it was closed in #234.
