### ISSUE TITLE
Create unit tests for uncovered lines in MerklePatriciaProof.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#241]
* `MerklePatriciaProof.sol` has the following coverage report 
46.43% Statements 52/112 
38% Branches 19/50 
83.33% Functions 5/6 
54.55% Lines 54/99
* Uncovered functions 
verify(43-46; 69-71), verifyDebug

**Comment by noslav** [comment]
Report currently stands at -
80.36% Statements 90/112
70% Branches 35/50
100% Functions 6/6
84.85% Lines 84/99

**Comment by schemar** [comment]
Dropped.
