### ISSUE TITLE
Create unit tests for uncovered lines in EIP20Token.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#245]
*`EIP20Token.sol` has the following coverage report
89.29% Statements 25/28 
100% Branches 0/0 
75% Functions 9/12 
89.29% Lines 25/28

* Uncovered Functions 
name, symbol, decimals

**Comment by noslav** [comment]
Report now stands at -
100% Statements 28/28
100% Branches 0/0
100% Functions 12/12
100% Lines 28/28

**Comment by schemar** [comment]
Dropped.
