### ISSUE TITLE
Create unit tests for uncovered lines in OpenSTUtility.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#246]
* `OpenSTUtility.sol` has the following coverage report 
95.8% Statements 137/143 
77.68% Branches 87/112 
81.25% Functions 13/16 
94.77% Lines 145/153

* Uncovered functions 
merkleVerificationOfStake, initiateProtocolTransfer, revokeProtocolTransfer

**Comment by schemar** [comment]
Dropped.
