### ISSUE TITLE
Create unit tests for uncovered lines in OpenSTValue.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#247]
* `OpenSTValue.sol` has the following coverage report 
95% Statements 114/120 
78.57% Branches 88/112 
82.35% Functions 14/17 
93.8% Lines 121/129

* Uncovered functions 
verifyRedemptionIntent, initiateProtocolTransfer, revokeProtocolTransfer

**Comment by schemar** [comment]
Dropped.
