### ISSUE TITLE
Create unit tests for uncovered lines in MockToken.sol

### ISSUE THREAD

**Issue by noslav** [OpenSTFoundation/mosaic-contracts#248]
* `MockToken.sol` has the following coverage report 
96% Statements 24/25 
100% Branches 0/0 
90.91% Functions 10/11 
96% Lines 24/25

* Uncovered functions 
remove

**Comment by noslav** [comment]
Report now stands at - 
100% Statements 25/25
100% Branches 0/0
100% Functions 11/11
100% Lines 25/25

**Comment by schemar** [comment]
Dropped.
