### ISSUE TITLE
MessageBus Library Contract Unit Testing

### ISSUE THREAD

**Issue by abhayks1** [OpenSTFoundation/mosaic-contracts#330]
We can start with the unit tests in the following order.

- declareMessage
- confirmMessage
- progressOutbox
- progressOutboxWithProof
- progressInbox
- progressInboxWithProof
 - declareRevocationMessage
 - confirmRevocation
 - progressRevocationMessage
 - revocationMessageDigest
 - messageDigest

**Comment by schemar** [comment]
Fixed in #352
