### ISSUE TITLE
A validator should be able to cast a vote

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/mosaic-contracts#371]
## User Story
As a validator
I want to cast Casper votes
Because I want to earn rewards for my votes.

## Scenario
Given that I am in the current set of validators
When I send a vote message
Then it should count according to my weight.

## Info
This story is about casting votes on reported checkpoints on auxiliary.

Contracts:
- PollingPlace

**Comment by schemar** [comment]
Transition object needs to be updated according to the paper in order to check for the correct transition hash.

**Comment by deepesh-kn** [comment]
The change for transition object is already handled in 
https://github.com/OpenSTFoundation/mosaic-contracts/pull/414
