### ISSUE TITLE
Validators should be able to commit a meta-block

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/mosaic-contracts#373]
## User Story
As a validator
I want to commit a meta-block
Because I want to avoid punishment for failing to do so.

## Scenario
Given that a meta-block was proposed
When I verify a corresponding vote signature
And a +2/3 majority of the weight is reached
Then the block should be committed
And all other open meta-block proposals should be purged.

## Info
The Kernel should have an empty validator change set for baby-mosaic.
The parent hash should be the hash of the parent *meta-block*, a typed hash that contains two typed hashes: kernel and transition object.

The commit should happen automatically when +2/3 is verified (during verification).

You need to delete (purge) all other open meta-block proposals, as they are no longer valid.

Contracts:
- OriginCore
- (Stake)

**Comment by schemar** [comment]
Committing a meta-block should create the new Kernel in storage.

**Comment by deepesh-kn** [comment]
While doing this, please see if test case for`OriginCore.getAccumulatedGasTarget()` needs to be updated
