### ISSUE TITLE
Anyone should be able to report a block header

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/mosaic-contracts#374]
## User Story
As a validator
I want to report a block header
Because I want to vote on Casper FFG checkpoints.

## Scenario
Given that I observed a block header
When I report that block header (to auxiliary)
Then the block is verified and recorded.

## Info
Contracts:
- BlockStore
- AuxiliaryBlockStore

**Comment by schemar** [comment]
The code probably exists already. If so, still make sure that it is in line with the paper.

**Comment by schemar** [comment]
The only verification should be that the parent (hash) has been reported before.

**Comment by deepesh-kn** [comment]
Code already exists. Parent hash and height checks are in place.
As per the paper the check to validate the block when its within the most recent 256 block is to be implemented. This part will be done in #386.
