### ISSUE TITLE
Validators should be able to verify a vote

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/mosaic-contracts#401]
## User Story
As a validator
I want to verify a vote
Because I want to commit a meta-block.

## Scenario
Given that a meta-block was proposed
When I verify a corresponding vote signature
Then it should count towards the seal.

## Info
Counting towards the seal means that it should count the weight that has been verified.
One message should only be verifiable once.
The contract should track the total weight (get from Stake), and the weight that has been verified (get from Stake for every verification).

Contracts:
- OriginCore
- (Stake)

**Comment by sarvesh-ost** [comment]
#444
