### ISSUE TITLE
JavaScript code linting and formatting

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/mosaic-contracts#404]
We should have standards for how JavaScript code is linted and formatted so it is homogeneous across files.

Copy the tools and settings from the openst repository that @pgev established.

Include auto-formatting of all existing files in this ticket.

Change indentation to `2` spaces.
Change line width hard wrap limit max character to `79` spaces.

**Comment by hobofan** [comment]
The basis for this was added with #458. The existing files in the `test` directory still need to be checked though.
