### ISSUE TITLE
Unit test all the functions of OSTPrime.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/mosaic-contracts#417]
## This story cover the following.
- Add unit tests for all the functions. (Please refer Utilitytoken test in openst-contract)
- Test of wrap and unwrap is already part of another ticket.
- Add Error message for requires if it is missing.

**Comment by schemar** [comment]
Please make sure that you fully test `claim` and `redeem` (`wrap` and `unwrap`).

Specifically:
```solidity
// Line 138 should probably not be `transfer`, but rather:
transferFrom(msg.sender, address(this), _amount);

// Line 163 should probably not be `transferFrom`, but rather:
transfer(msg.sender, _amount);
```

Looks like a bug.
