### ISSUE TITLE
Rename `claim` and `redeem` function names in OST prime contract.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/mosaic-contracts#498]
- Rename the functions in the OST prime from `claim` to `unwrap` and `redeem` to `wrap`.

**Comment by seshanthS** [comment]
Renamed the function names . Commit 44e0efd 

https://github.com/OpenSTFoundation/mosaic-contracts/commit/44e0efd17d0c21b16bfb8db8d5ffb3a3f567924b
