### ISSUE TITLE
Rename `mint` and `burn` functions name in the UtilityTokenInterface.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/mosaic-contracts#499]
[Discuss with team, this is not yet finalized.]
- Rename the functions in the UtilityTokenInterface from `Mint` to `increaseSupply` and `burn` to `decreaseSupply`.
- EIP20 CoGateway should be updated accordingly.
- We may also think to re-introduce UtilityTokenAbstract (Discuss this with the team).

**Comment by deepesh-kn** [comment]
ref: https://github.com/ethereum/EIPs/pull/621

**Comment by schemar** [comment]
@deepesh-kn:
> Considering that we will use OpenST-contracts utility token, we may not need utility token abstract.
