### ISSUE TITLE
Improve code pattern `EIP20CoGateway.progressRedeemInternal`

### ISSUE THREAD

**Issue by benjaminbollen** [OpenSTFoundation/mosaic-contracts#605]
In `EIP20CoGateway.progressRedeemInternal` the `bounty` is returned to the successful facilitator (`msg.sender`) progressing the redemption (with proof or hashlock).  This `(msg.sender).transfer` is an external call, and a re-entrancy attack is of concern.

Two external functions, `progressRedeem` and `progressRedeemWithProof` check and update the state before calling `progressRedeemInternal`, so a re-entrancy attack is not possible.  However, within `progressRedeemInternal` the `redeems` mapping entry is deleted after the `.transfer`.

It is better to delete the mapping first and check on existence of the entry, before calling `.transfer`

https://github.com/OpenSTFoundation/mosaic-contracts/blob/develop/contracts/gateway/EIP20CoGateway.sol#L1130-L1134

ℹ️ Check other places where the base token is transferred.
- EIP20Gateway.progressStakeInternal
- EIP20Gateway.progressRevertStake
- EIP20Gateway.progressUnstakeInternal
- EIP20CoGateway.progressRevertRedeem
- EIP20CoGateway.progressRedeemInternal
- EIP20CoGateway.progressMintInternal
- OSTPrime.unwrap
- OSTPrime.increaseSupply

**Comment by deepesh-kn** [comment]
Deepesh will add all the possible location that may need this changes.
