### ISSUE TITLE
Set-up integration test environment 

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenSTFoundation/mosaic-contracts#608]
The integration test environment should consist of two chains, one geth node each. @hobofan can advise in how to easily get that up and running.

Then, the integration tests should use "chain deployment" to deploy the contracts.

Mocha and Chai should be used to test the functionality.

Integration tests should be run with a separate npm command.

Refer:
- https://github.com/OpenSTFoundation/chains-utils
- https://hub.docker.com/r/ethereum/client-go

**Comment by schemar** [comment]
Some things I found out so far:
We do not have access to the Truffle artifacts (contract abstractions) in our tests, unless we use `truffle exec ...js` (allegedly, I didn't even get that to work, yet).
Running `truffle exec ...` always requires a *running node* when starting the command 🤦‍♂️

I am afraid we may have to use web3 contracts for integration tests 🙀

/cc @sarvesh-ost @hobofan

**Comment by schemar** [comment]
OK it works, but it still requires a dummy ganache to even start 😅
I may put startup and teardown of docker into a separate script that invokes the integration tests in-between. 🤔

**Comment by schemar** [comment]
Yeah. Everything works with the dummy ganache running. Tomorrow I will extract set-up and teardown. I think then it's ready to roll. We need to merge your PR @hobofan 😜
