### ISSUE TITLE
Clean-up

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/mosaic-contracts#630]
Clean up the following before release:
* move contracts in the `contracts` directory into the appropriate sub-directory (`lib`)
* delete unused files:
  * protocol versioned
  * test utils
  * check for more

**Comment by schemar** [comment]
@sarvesh-ost @deepesh-kn @hobofan please add anything you can think of to this ticket.

**Comment by hobofan** [comment]
#604

**Comment by schemar** [comment]
All set in separate tickets
